### PR TITLE
Fix: Text input schema needs top level answers (fixes #114)

### LINKED ISSUE #114: Text input schema needs top level answers

### PR DESCRIPTION
**Pull request by lemmyadams**
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)

[//]: # (Link the PR to the original issue)
Addresses #114 

[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
### Fix
* Adds top level _answers property to the schema. 

This is particularly important as one of the latest PRs now unconditionally checks for this. [See screenshot]. This now fails because there's no _answers array to retrieve, and you can't perform a slice() method on something undefined

Screenshot 2024-10-29 at 13 24 10

### CODE REVIEW

**Comment by oliverfoster** [comment]
"_answers" is an array of arrays of strings - an answer and its aliases can only be used once

Yours:
```json
[
      "North America",
      "N America",
      "N. America"
]
```

Configuration:
```json
[
      ["Asia"],
      ["Africa"],
      ["North America","N America", "N. America"],
      ["South America","S America", "S. America"],
      ["Europe"],
      ["Antarctica"],
      ["Australia"]
]
```

**Comment by oliverfoster** [comment]
This needs testing in an AAT now. I was quite sure the it wasn't possible to specify a schema that does this. As per https://github.com/adaptlearning/adapt-contrib-textInput/issues/114#issuecomment-1198194447

**Comment by swashbuck** [comment]
> @oliverfoster I've updated it to be an array of strings. I'm unsure on what it should exactly be so let me know if there's anything further needed to change

@lemmyadams Does this still allow for aliases / alternate spellings? For instance, if the question is "List the names of seven continents", we would not want users to get two correct answers if they enter both "North America" and "N. America" since they are the same continent.

**Comment by cahirodoherty-learningpool** [comment]
Hi Lemmy, I believe this can be closed off now

**Pull request closed without merging**
