### PR TITLE
Marking fix

### PR DESCRIPTION
**Pull request by taylortom**
Allows answers to be specified at a question-level, rather than having to specify per input. Allows user to answer in any order.

### CODE REVIEW

**Comment by hrajotia** [comment]
+1

**Comment by oliverfoster** [comment]
+1

**Comment by brian-learningpool** [comment]
@taylortom, won't expecting parameters in a two dimensional array break backwards compatibility with existing JSON?

**Comment by taylortom** [comment]
The _answers array specified at the top level is optional; if the old style answers are provided (i.e. per input), this will work as before. You can also use a combination of the two (e.g. have a specific answer for one input, and an unordered list for the rest).

See https://github.com/taylortom/adapt-contrib-textInput/blob/markingFix/js/adapt-contrib-textInput.js#L99-L100

**Comment by brian-learningpool** [comment]
Cool.  Thanks for clarifying.

**Comment by brian-learningpool** [comment]
+1

**Pull request merged**
