### PR TITLE
Fix: save and restore issues with new features

### PR DESCRIPTION
**Pull request by oliverfoster**
* made sure restoring answers takes the first correct item in the array if generic answers is an array
* made sure marking answers doesn't destroy answerItems indexes in the saving process

### CODE REVIEW

**Comment by oliverfoster** [comment]
https://github.com/adaptlearning/adapt-contrib-spoor/pull/82 < needs this or to fix also

**Comment by moloko** [comment]
+1

**Comment by belal-almassri-spongeuk** [comment]
+1

**Comment by zenduo** [comment]
+1

**Pull request merged**
